# Dataset Size and Split Parameters
dataset_params:
  train_images: 1
  val_images: 1
  train_split: 0.8

# Image Shape
shape:
  height: 1080
  width: 1920
  
# Object Categories and Corresponding Category IDs. 
# (int, required): an integer in the range [0, num_categories-1] representing the category label. 
# The value num_categories is reserved to represent the “background” category, if applicable.
categories:
  device: 1
  wire: 2
  background: 3

# Color Thresholding Values for Each Object Category
color_threshold:
  device: 50
  wire: 30

# Contur Minimum Area (in pixels) Threshold Value
contour_threshold: 1000
  
# Maximum Number of Instances Per Image for Each Object Category
max_instances:
  device: 2
  wire: 4

# Parameters for Scale Jittering
scale_jittering:
  apply_scale_jittering: true

  # if true, different objects use different scale factors
  individual_scale_jittering: true

  # scale factor range
  scale_factor_min: 0.75
  scale_factor_max: 1.25

# Parameters for Color Augmentation
color_augmentation:
  apply_color_augmentation: true

  # if true, different objects use different values
  individual_color_augmentation: true
  change_saturation: true
  change_brightness: true
  change_contrast: true
  change_hue: true

  # Lower/Upper Limit of Color Augmentation
  enhancer_min: 0.75
  enhancer_max: 1.25

  # if true, apply color augmentation again to the combined image
  color_augmentation_on_combined_image: true

# Flag to designate whether the demo is performed
demo_dataset: True

# Flag to designate whether to train a model from the detectron2 model zoo on the generated dataset
train_detectron2: False

# Parameters for which dataset to visualize and how many annotated images from the dataset to visualize.
# Options: "train" and "val"
dataset_verification:
  which_dataset: "val"
  number_of_images: 2

# User defined parameters
directory:
  root_dir: "."
  dataset_directory_name: "test"
  AZURE_STORAGE_CONNECTION_STRING: 'DefaultEndpointsProtocol=https;AccountName=uiucwiresdataset;AccountKey=VkJ1HT3LkDuiLTFK8yd+eAFLvhLKJNqLDIealTPY9Lv6Dp7VDFVWKIvhnNXqC+GCQYjh7NQVuH1r+ASt/tVk7g==;EndpointSuffix=core.windows.net'