# Dataset Size and Split Parameters
dataset_params:
  train_images: 5
  val_images: 3
  train_split: 0.8

# Image Shape
shape:
  height: 1080
  width: 1920
  
# Object Categories and Corresponding Category IDs
categories:
  background: 0
  device: 1
  wire: 2

# Color Thresholding Values for Each Object Category
threshold:
  device: 50
  wire: 30
  
# Maximum Number of Instances Per Image for Each Object Category
max_instances:
  device: 2
  wire: 4

# User defined parameters
directory:
  root_dir: "."
  dataset_directory_name: "cocopen-dataset"
  AZURE_STORAGE_CONNECTION_STRING: 'DefaultEndpointsProtocol=https;AccountName=uiucwiresdataset;AccountKey=VkJ1HT3LkDuiLTFK8yd+eAFLvhLKJNqLDIealTPY9Lv6Dp7VDFVWKIvhnNXqC+GCQYjh7NQVuH1r+ASt/tVk7g==;EndpointSuffix=core.windows.net'